name: Deploy Node.js Backend with PM2

on:
  push:
    branches:
      - master  # or main if you're using that

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e  # Exit on error

            
            cd /home/ubuntu/backend/crm-backend

            # If repo not cloned yet, clone it
            if [ ! -d ".git" ]; then
              echo "Cloning repository..."
              rm -rf crm-backend  # Clean up any old files
              git clone https://github.com/Gappu12sh/backend.git crm-backend
            else
              echo "Pulling latest changes..."
              git pull origin master
            fi
            npm install

            # Restart or start app with PM2
            if pm2 list | grep -q "backend"; then
              pm2 restart backend
            else
              pm2 start server.js --name "backend"
            fi
          EOF
