name: Deploy Node.js Backend with PM2
 
on:
  push:
    branches:
      - main  # or the branch you use for deployment
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
 
    - name: Deploy to Server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          # Check if the directory exists
          if [ -d "/home/ubuntu/backend/crm-backend-main" ]; then
            cd /home/ubuntu/backend/crm-backend-main
            git pull origin main
            npm install
            pm2 restart server.js --name "backend"
          else
            echo "Directory does not exist!"
          fi
        EOF
